apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: enduro-sdps
resources:
  - ../../base
  - mysql-recreate-databases-job.yaml
  - mysql-secret.yaml
  - preprocessing-secret.yaml
  - start-workflow-job.yaml
