apiVersion: v1
kind: Secret
metadata:
  name: preprocessing-secret
type: Opaque
stringData:
  preprocessing.toml: |
    debug = true
    verbosity = 2

    sharedPath = "/home/preprocessing/shared"

    [temporal]
    address = "temporal.enduro-sdps:7233"
    namespace = "default"
    taskQueue = "preprocessing"
    workflowName = "preprocessing"

    [worker]
    maxConcurrentSessions = 1

    [bagit]
    checksumAlgorithm = "md5"

    [ais]
    listen = "0.0.0.0:9035"
    workingDir = "/tmp"

    [ais.temporal]
    address = "temporal.enduro-sdps:7233"
    namespace = "default"
    taskQueue = "ais"
    workflowName = "ais"

    [ais.worker]
    maxConcurrentSessions = 1

    [ais.amss]
    url = "http://host.k3d.internal:62081"
    user = "test"
    key = "test"

    [ais.bucket]
    endpoint = "http://minio.enduro-sdps:9000"
    pathStyle = true
    accessKey = "minio"
    secretKey = "minio123"
    region = "us-west-1"
    bucket = "ais"
