// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/artefactual-sdps/preprocessing-sfa/internal/persistence/ent/db/predicate"
	"github.com/artefactual-sdps/preprocessing-sfa/internal/persistence/ent/db/sip"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeSIP = "SIP"
)

// SIPMutation represents an operation that mutates the SIP nodes in the graph.
type SIPMutation struct {
	config
	op            Op
	typ           string
	id            *int
	name          *string
	checksum      *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*SIP, error)
	predicates    []predicate.SIP
}

var _ ent.Mutation = (*SIPMutation)(nil)

// sipOption allows management of the mutation configuration using functional options.
type sipOption func(*SIPMutation)

// newSIPMutation creates new mutation for the SIP entity.
func newSIPMutation(c config, op Op, opts ...sipOption) *SIPMutation {
	m := &SIPMutation{
		config:        c,
		op:            op,
		typ:           TypeSIP,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withSIPID sets the ID field of the mutation.
func withSIPID(id int) sipOption {
	return func(m *SIPMutation) {
		var (
			err   error
			once  sync.Once
			value *SIP
		)
		m.oldValue = func(ctx context.Context) (*SIP, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().SIP.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withSIP sets the old SIP of the mutation.
func withSIP(node *SIP) sipOption {
	return func(m *SIPMutation) {
		m.oldValue = func(context.Context) (*SIP, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m SIPMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m SIPMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("db: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *SIPMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *SIPMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().SIP.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *SIPMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *SIPMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the SIP entity.
// If the SIP object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SIPMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *SIPMutation) ResetName() {
	m.name = nil
}

// SetChecksum sets the "checksum" field.
func (m *SIPMutation) SetChecksum(s string) {
	m.checksum = &s
}

// Checksum returns the value of the "checksum" field in the mutation.
func (m *SIPMutation) Checksum() (r string, exists bool) {
	v := m.checksum
	if v == nil {
		return
	}
	return *v, true
}

// OldChecksum returns the old "checksum" field's value of the SIP entity.
// If the SIP object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SIPMutation) OldChecksum(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldChecksum is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldChecksum requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldChecksum: %w", err)
	}
	return oldValue.Checksum, nil
}

// ResetChecksum resets all changes to the "checksum" field.
func (m *SIPMutation) ResetChecksum() {
	m.checksum = nil
}

// Where appends a list predicates to the SIPMutation builder.
func (m *SIPMutation) Where(ps ...predicate.SIP) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the SIPMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *SIPMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.SIP, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *SIPMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *SIPMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (SIP).
func (m *SIPMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *SIPMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.name != nil {
		fields = append(fields, sip.FieldName)
	}
	if m.checksum != nil {
		fields = append(fields, sip.FieldChecksum)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *SIPMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case sip.FieldName:
		return m.Name()
	case sip.FieldChecksum:
		return m.Checksum()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *SIPMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case sip.FieldName:
		return m.OldName(ctx)
	case sip.FieldChecksum:
		return m.OldChecksum(ctx)
	}
	return nil, fmt.Errorf("unknown SIP field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SIPMutation) SetField(name string, value ent.Value) error {
	switch name {
	case sip.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case sip.FieldChecksum:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetChecksum(v)
		return nil
	}
	return fmt.Errorf("unknown SIP field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *SIPMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *SIPMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SIPMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown SIP numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *SIPMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *SIPMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *SIPMutation) ClearField(name string) error {
	return fmt.Errorf("unknown SIP nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *SIPMutation) ResetField(name string) error {
	switch name {
	case sip.FieldName:
		m.ResetName()
		return nil
	case sip.FieldChecksum:
		m.ResetChecksum()
		return nil
	}
	return fmt.Errorf("unknown SIP field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *SIPMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *SIPMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *SIPMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *SIPMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *SIPMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *SIPMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *SIPMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown SIP unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *SIPMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown SIP edge %s", name)
}
