// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/artefactual-sdps/preprocessing-sfa/internal/persistence/ent/db/predicate"
	"github.com/artefactual-sdps/preprocessing-sfa/internal/persistence/ent/db/sip"
)

// SIPUpdate is the builder for updating SIP entities.
type SIPUpdate struct {
	config
	hooks    []Hook
	mutation *SIPMutation
}

// Where appends a list predicates to the SIPUpdate builder.
func (_u *SIPUpdate) Where(ps ...predicate.SIP) *SIPUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *SIPUpdate) SetName(v string) *SIPUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SIPUpdate) SetNillableName(v *string) *SIPUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetChecksum sets the "checksum" field.
func (_u *SIPUpdate) SetChecksum(v string) *SIPUpdate {
	_u.mutation.SetChecksum(v)
	return _u
}

// SetNillableChecksum sets the "checksum" field if the given value is not nil.
func (_u *SIPUpdate) SetNillableChecksum(v *string) *SIPUpdate {
	if v != nil {
		_u.SetChecksum(*v)
	}
	return _u
}

// Mutation returns the SIPMutation object of the builder.
func (_u *SIPUpdate) Mutation() *SIPMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SIPUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SIPUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SIPUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SIPUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SIPUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(sip.Table, sip.Columns, sqlgraph.NewFieldSpec(sip.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(sip.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Checksum(); ok {
		_spec.SetField(sip.FieldChecksum, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sip.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SIPUpdateOne is the builder for updating a single SIP entity.
type SIPUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SIPMutation
}

// SetName sets the "name" field.
func (_u *SIPUpdateOne) SetName(v string) *SIPUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SIPUpdateOne) SetNillableName(v *string) *SIPUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetChecksum sets the "checksum" field.
func (_u *SIPUpdateOne) SetChecksum(v string) *SIPUpdateOne {
	_u.mutation.SetChecksum(v)
	return _u
}

// SetNillableChecksum sets the "checksum" field if the given value is not nil.
func (_u *SIPUpdateOne) SetNillableChecksum(v *string) *SIPUpdateOne {
	if v != nil {
		_u.SetChecksum(*v)
	}
	return _u
}

// Mutation returns the SIPMutation object of the builder.
func (_u *SIPUpdateOne) Mutation() *SIPMutation {
	return _u.mutation
}

// Where appends a list predicates to the SIPUpdate builder.
func (_u *SIPUpdateOne) Where(ps ...predicate.SIP) *SIPUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SIPUpdateOne) Select(field string, fields ...string) *SIPUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SIP entity.
func (_u *SIPUpdateOne) Save(ctx context.Context) (*SIP, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SIPUpdateOne) SaveX(ctx context.Context) *SIP {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SIPUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SIPUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SIPUpdateOne) sqlSave(ctx context.Context) (_node *SIP, err error) {
	_spec := sqlgraph.NewUpdateSpec(sip.Table, sip.Columns, sqlgraph.NewFieldSpec(sip.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`db: missing "SIP.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sip.FieldID)
		for _, f := range fields {
			if !sip.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
			}
			if f != sip.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(sip.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Checksum(); ok {
		_spec.SetField(sip.FieldChecksum, field.TypeString, value)
	}
	_node = &SIP{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sip.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
