apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: enduro-sdps
resources:
  - apis-mock
  - mysql.yaml
  - namespace.yaml
  - preprocessing-worker
  - role.yaml
  - role-binding.yaml
  - service-account.yaml
  - temporal-ui.yaml
  - temporal.yaml
