apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: preprocessing-worker
  labels:
    app: preprocessing-worker
spec:
  serviceName: preprocessing-worker
  selector:
    matchLabels:
      app: preprocessing-worker
  template:
    metadata:
      labels:
        app: preprocessing-worker
    spec:
      serviceAccountName: sdps
      securityContext:
        fsGroup: 1000
      containers:
        - name: preprocessing-worker
          image: preprocessing-sfa-worker:dev
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: ENDURO_PREPROCESSING_PERSISTENCE_DSN
              value: $(MYSQL_USER):$(MYSQL_PASSWORD)@tcp(mysql.enduro-sdps:3306)/preprocessing_sfa
          volumeMounts:
            - name: config
              mountPath: /home/preprocessing/.config
              readOnly: true
          resources: {}
      volumes:
        - name: config
          secret:
            secretName: preprocessing-secret
