// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/artefactual-sdps/preprocessing-sfa/internal/amss (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -typed -destination=./internal/amss/fake/mock_service.go -package=fake github.com/artefactual-sdps/preprocessing-sfa/internal/amss Service
//

// Package fake is a generated GoMock package.
package fake

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// DownloadAIPFile mocks base method.
func (m *MockService) DownloadAIPFile(arg0 context.Context, arg1, arg2 string, arg3 io.Writer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadAIPFile", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownloadAIPFile indicates an expected call of DownloadAIPFile.
func (mr *MockServiceMockRecorder) DownloadAIPFile(arg0, arg1, arg2, arg3 any) *MockServiceDownloadAIPFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadAIPFile", reflect.TypeOf((*MockService)(nil).DownloadAIPFile), arg0, arg1, arg2, arg3)
	return &MockServiceDownloadAIPFileCall{Call: call}
}

// MockServiceDownloadAIPFileCall wrap *gomock.Call
type MockServiceDownloadAIPFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceDownloadAIPFileCall) Return(arg0 error) *MockServiceDownloadAIPFileCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceDownloadAIPFileCall) Do(f func(context.Context, string, string, io.Writer) error) *MockServiceDownloadAIPFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceDownloadAIPFileCall) DoAndReturn(f func(context.Context, string, string, io.Writer) error) *MockServiceDownloadAIPFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetAIPPath mocks base method.
func (m *MockService) GetAIPPath(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAIPPath", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAIPPath indicates an expected call of GetAIPPath.
func (mr *MockServiceMockRecorder) GetAIPPath(arg0, arg1 any) *MockServiceGetAIPPathCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAIPPath", reflect.TypeOf((*MockService)(nil).GetAIPPath), arg0, arg1)
	return &MockServiceGetAIPPathCall{Call: call}
}

// MockServiceGetAIPPathCall wrap *gomock.Call
type MockServiceGetAIPPathCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceGetAIPPathCall) Return(arg0 string, arg1 error) *MockServiceGetAIPPathCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceGetAIPPathCall) Do(f func(context.Context, string) (string, error)) *MockServiceGetAIPPathCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceGetAIPPathCall) DoAndReturn(f func(context.Context, string) (string, error)) *MockServiceGetAIPPathCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
