// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/artefactual-sdps/preprocessing-sfa/internal/apis (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -typed -destination=./internal/apis/fake/mock_client.go -package=fake github.com/artefactual-sdps/preprocessing-sfa/internal/apis Client
//

// Package fake is a generated GoMock package.
package fake

import (
	context "context"
	reflect "reflect"

	gen "github.com/artefactual-sdps/preprocessing-sfa/internal/apis/gen"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// APIHealthzGet mocks base method.
func (m *MockClient) APIHealthzGet(ctx context.Context) (gen.APIHealthzGetRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APIHealthzGet", ctx)
	ret0, _ := ret[0].(gen.APIHealthzGetRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// APIHealthzGet indicates an expected call of APIHealthzGet.
func (mr *MockClientMockRecorder) APIHealthzGet(ctx any) *MockClientAPIHealthzGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APIHealthzGet", reflect.TypeOf((*MockClient)(nil).APIHealthzGet), ctx)
	return &MockClientAPIHealthzGetCall{Call: call}
}

// MockClientAPIHealthzGetCall wrap *gomock.Call
type MockClientAPIHealthzGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientAPIHealthzGetCall) Return(arg0 gen.APIHealthzGetRes, arg1 error) *MockClientAPIHealthzGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientAPIHealthzGetCall) Do(f func(context.Context) (gen.APIHealthzGetRes, error)) *MockClientAPIHealthzGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientAPIHealthzGetCall) DoAndReturn(f func(context.Context) (gen.APIHealthzGetRes, error)) *MockClientAPIHealthzGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// APIImporttasksIDCancelPost mocks base method.
func (m *MockClient) APIImporttasksIDCancelPost(ctx context.Context, request gen.APIImporttasksIDCancelPostReq, params gen.APIImporttasksIDCancelPostParams) (gen.APIImporttasksIDCancelPostRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APIImporttasksIDCancelPost", ctx, request, params)
	ret0, _ := ret[0].(gen.APIImporttasksIDCancelPostRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// APIImporttasksIDCancelPost indicates an expected call of APIImporttasksIDCancelPost.
func (mr *MockClientMockRecorder) APIImporttasksIDCancelPost(ctx, request, params any) *MockClientAPIImporttasksIDCancelPostCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APIImporttasksIDCancelPost", reflect.TypeOf((*MockClient)(nil).APIImporttasksIDCancelPost), ctx, request, params)
	return &MockClientAPIImporttasksIDCancelPostCall{Call: call}
}

// MockClientAPIImporttasksIDCancelPostCall wrap *gomock.Call
type MockClientAPIImporttasksIDCancelPostCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientAPIImporttasksIDCancelPostCall) Return(arg0 gen.APIImporttasksIDCancelPostRes, arg1 error) *MockClientAPIImporttasksIDCancelPostCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientAPIImporttasksIDCancelPostCall) Do(f func(context.Context, gen.APIImporttasksIDCancelPostReq, gen.APIImporttasksIDCancelPostParams) (gen.APIImporttasksIDCancelPostRes, error)) *MockClientAPIImporttasksIDCancelPostCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientAPIImporttasksIDCancelPostCall) DoAndReturn(f func(context.Context, gen.APIImporttasksIDCancelPostReq, gen.APIImporttasksIDCancelPostParams) (gen.APIImporttasksIDCancelPostRes, error)) *MockClientAPIImporttasksIDCancelPostCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// APIImporttasksIDImportrunsPost mocks base method.
func (m *MockClient) APIImporttasksIDImportrunsPost(ctx context.Context, request gen.OptAPIImporttasksIDImportrunsPostReq, params gen.APIImporttasksIDImportrunsPostParams) (gen.APIImporttasksIDImportrunsPostRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APIImporttasksIDImportrunsPost", ctx, request, params)
	ret0, _ := ret[0].(gen.APIImporttasksIDImportrunsPostRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// APIImporttasksIDImportrunsPost indicates an expected call of APIImporttasksIDImportrunsPost.
func (mr *MockClientMockRecorder) APIImporttasksIDImportrunsPost(ctx, request, params any) *MockClientAPIImporttasksIDImportrunsPostCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APIImporttasksIDImportrunsPost", reflect.TypeOf((*MockClient)(nil).APIImporttasksIDImportrunsPost), ctx, request, params)
	return &MockClientAPIImporttasksIDImportrunsPostCall{Call: call}
}

// MockClientAPIImporttasksIDImportrunsPostCall wrap *gomock.Call
type MockClientAPIImporttasksIDImportrunsPostCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientAPIImporttasksIDImportrunsPostCall) Return(arg0 gen.APIImporttasksIDImportrunsPostRes, arg1 error) *MockClientAPIImporttasksIDImportrunsPostCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientAPIImporttasksIDImportrunsPostCall) Do(f func(context.Context, gen.OptAPIImporttasksIDImportrunsPostReq, gen.APIImporttasksIDImportrunsPostParams) (gen.APIImporttasksIDImportrunsPostRes, error)) *MockClientAPIImporttasksIDImportrunsPostCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientAPIImporttasksIDImportrunsPostCall) DoAndReturn(f func(context.Context, gen.OptAPIImporttasksIDImportrunsPostReq, gen.APIImporttasksIDImportrunsPostParams) (gen.APIImporttasksIDImportrunsPostRes, error)) *MockClientAPIImporttasksIDImportrunsPostCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// APIImporttasksIDImportrunsRunIdStatusGet mocks base method.
func (m *MockClient) APIImporttasksIDImportrunsRunIdStatusGet(ctx context.Context, params gen.APIImporttasksIDImportrunsRunIdStatusGetParams) (gen.APIImporttasksIDImportrunsRunIdStatusGetRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APIImporttasksIDImportrunsRunIdStatusGet", ctx, params)
	ret0, _ := ret[0].(gen.APIImporttasksIDImportrunsRunIdStatusGetRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// APIImporttasksIDImportrunsRunIdStatusGet indicates an expected call of APIImporttasksIDImportrunsRunIdStatusGet.
func (mr *MockClientMockRecorder) APIImporttasksIDImportrunsRunIdStatusGet(ctx, params any) *MockClientAPIImporttasksIDImportrunsRunIdStatusGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APIImporttasksIDImportrunsRunIdStatusGet", reflect.TypeOf((*MockClient)(nil).APIImporttasksIDImportrunsRunIdStatusGet), ctx, params)
	return &MockClientAPIImporttasksIDImportrunsRunIdStatusGetCall{Call: call}
}

// MockClientAPIImporttasksIDImportrunsRunIdStatusGetCall wrap *gomock.Call
type MockClientAPIImporttasksIDImportrunsRunIdStatusGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientAPIImporttasksIDImportrunsRunIdStatusGetCall) Return(arg0 gen.APIImporttasksIDImportrunsRunIdStatusGetRes, arg1 error) *MockClientAPIImporttasksIDImportrunsRunIdStatusGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientAPIImporttasksIDImportrunsRunIdStatusGetCall) Do(f func(context.Context, gen.APIImporttasksIDImportrunsRunIdStatusGetParams) (gen.APIImporttasksIDImportrunsRunIdStatusGetRes, error)) *MockClientAPIImporttasksIDImportrunsRunIdStatusGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientAPIImporttasksIDImportrunsRunIdStatusGetCall) DoAndReturn(f func(context.Context, gen.APIImporttasksIDImportrunsRunIdStatusGetParams) (gen.APIImporttasksIDImportrunsRunIdStatusGetRes, error)) *MockClientAPIImporttasksIDImportrunsRunIdStatusGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// APIImporttasksIDStatusGet mocks base method.
func (m *MockClient) APIImporttasksIDStatusGet(ctx context.Context, params gen.APIImporttasksIDStatusGetParams) (gen.APIImporttasksIDStatusGetRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APIImporttasksIDStatusGet", ctx, params)
	ret0, _ := ret[0].(gen.APIImporttasksIDStatusGetRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// APIImporttasksIDStatusGet indicates an expected call of APIImporttasksIDStatusGet.
func (mr *MockClientMockRecorder) APIImporttasksIDStatusGet(ctx, params any) *MockClientAPIImporttasksIDStatusGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APIImporttasksIDStatusGet", reflect.TypeOf((*MockClient)(nil).APIImporttasksIDStatusGet), ctx, params)
	return &MockClientAPIImporttasksIDStatusGetCall{Call: call}
}

// MockClientAPIImporttasksIDStatusGetCall wrap *gomock.Call
type MockClientAPIImporttasksIDStatusGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientAPIImporttasksIDStatusGetCall) Return(arg0 gen.APIImporttasksIDStatusGetRes, arg1 error) *MockClientAPIImporttasksIDStatusGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientAPIImporttasksIDStatusGetCall) Do(f func(context.Context, gen.APIImporttasksIDStatusGetParams) (gen.APIImporttasksIDStatusGetRes, error)) *MockClientAPIImporttasksIDStatusGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientAPIImporttasksIDStatusGetCall) DoAndReturn(f func(context.Context, gen.APIImporttasksIDStatusGetParams) (gen.APIImporttasksIDStatusGetRes, error)) *MockClientAPIImporttasksIDStatusGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// APIImporttasksPost mocks base method.
func (m *MockClient) APIImporttasksPost(ctx context.Context, request gen.OptAPIImporttasksPostReq) (gen.APIImporttasksPostRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APIImporttasksPost", ctx, request)
	ret0, _ := ret[0].(gen.APIImporttasksPostRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// APIImporttasksPost indicates an expected call of APIImporttasksPost.
func (mr *MockClientMockRecorder) APIImporttasksPost(ctx, request any) *MockClientAPIImporttasksPostCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APIImporttasksPost", reflect.TypeOf((*MockClient)(nil).APIImporttasksPost), ctx, request)
	return &MockClientAPIImporttasksPostCall{Call: call}
}

// MockClientAPIImporttasksPostCall wrap *gomock.Call
type MockClientAPIImporttasksPostCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientAPIImporttasksPostCall) Return(arg0 gen.APIImporttasksPostRes, arg1 error) *MockClientAPIImporttasksPostCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientAPIImporttasksPostCall) Do(f func(context.Context, gen.OptAPIImporttasksPostReq) (gen.APIImporttasksPostRes, error)) *MockClientAPIImporttasksPostCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientAPIImporttasksPostCall) DoAndReturn(f func(context.Context, gen.OptAPIImporttasksPostReq) (gen.APIImporttasksPostRes, error)) *MockClientAPIImporttasksPostCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
