// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/artefactual-sdps/preprocessing-sfa/internal/apis (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -typed -destination=./internal/apis/fake/mock_client.go -package=fake github.com/artefactual-sdps/preprocessing-sfa/internal/apis Client
//

// Package fake is a generated GoMock package.
package fake

import (
	context "context"
	reflect "reflect"

	gen "github.com/artefactual-sdps/preprocessing-sfa/internal/apis/gen"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// APIHealthzGet mocks base method.
func (m *MockClient) APIHealthzGet(ctx context.Context) (gen.APIHealthzGetRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APIHealthzGet", ctx)
	ret0, _ := ret[0].(gen.APIHealthzGetRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// APIHealthzGet indicates an expected call of APIHealthzGet.
func (mr *MockClientMockRecorder) APIHealthzGet(ctx any) *MockClientAPIHealthzGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APIHealthzGet", reflect.TypeOf((*MockClient)(nil).APIHealthzGet), ctx)
	return &MockClientAPIHealthzGetCall{Call: call}
}

// MockClientAPIHealthzGetCall wrap *gomock.Call
type MockClientAPIHealthzGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientAPIHealthzGetCall) Return(arg0 gen.APIHealthzGetRes, arg1 error) *MockClientAPIHealthzGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientAPIHealthzGetCall) Do(f func(context.Context) (gen.APIHealthzGetRes, error)) *MockClientAPIHealthzGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientAPIHealthzGetCall) DoAndReturn(f func(context.Context) (gen.APIHealthzGetRes, error)) *MockClientAPIHealthzGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// APIImportTasksIDImportRunsPost mocks base method.
func (m *MockClient) APIImportTasksIDImportRunsPost(ctx context.Context, request gen.OptAPIImportTasksIDImportRunsPostReq, params gen.APIImportTasksIDImportRunsPostParams) (gen.APIImportTasksIDImportRunsPostRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APIImportTasksIDImportRunsPost", ctx, request, params)
	ret0, _ := ret[0].(gen.APIImportTasksIDImportRunsPostRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// APIImportTasksIDImportRunsPost indicates an expected call of APIImportTasksIDImportRunsPost.
func (mr *MockClientMockRecorder) APIImportTasksIDImportRunsPost(ctx, request, params any) *MockClientAPIImportTasksIDImportRunsPostCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APIImportTasksIDImportRunsPost", reflect.TypeOf((*MockClient)(nil).APIImportTasksIDImportRunsPost), ctx, request, params)
	return &MockClientAPIImportTasksIDImportRunsPostCall{Call: call}
}

// MockClientAPIImportTasksIDImportRunsPostCall wrap *gomock.Call
type MockClientAPIImportTasksIDImportRunsPostCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientAPIImportTasksIDImportRunsPostCall) Return(arg0 gen.APIImportTasksIDImportRunsPostRes, arg1 error) *MockClientAPIImportTasksIDImportRunsPostCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientAPIImportTasksIDImportRunsPostCall) Do(f func(context.Context, gen.OptAPIImportTasksIDImportRunsPostReq, gen.APIImportTasksIDImportRunsPostParams) (gen.APIImportTasksIDImportRunsPostRes, error)) *MockClientAPIImportTasksIDImportRunsPostCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientAPIImportTasksIDImportRunsPostCall) DoAndReturn(f func(context.Context, gen.OptAPIImportTasksIDImportRunsPostReq, gen.APIImportTasksIDImportRunsPostParams) (gen.APIImportTasksIDImportRunsPostRes, error)) *MockClientAPIImportTasksIDImportRunsPostCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// APIImportTasksIDImportRunsRunIdStatusGet mocks base method.
func (m *MockClient) APIImportTasksIDImportRunsRunIdStatusGet(ctx context.Context, params gen.APIImportTasksIDImportRunsRunIdStatusGetParams) (gen.APIImportTasksIDImportRunsRunIdStatusGetRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APIImportTasksIDImportRunsRunIdStatusGet", ctx, params)
	ret0, _ := ret[0].(gen.APIImportTasksIDImportRunsRunIdStatusGetRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// APIImportTasksIDImportRunsRunIdStatusGet indicates an expected call of APIImportTasksIDImportRunsRunIdStatusGet.
func (mr *MockClientMockRecorder) APIImportTasksIDImportRunsRunIdStatusGet(ctx, params any) *MockClientAPIImportTasksIDImportRunsRunIdStatusGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APIImportTasksIDImportRunsRunIdStatusGet", reflect.TypeOf((*MockClient)(nil).APIImportTasksIDImportRunsRunIdStatusGet), ctx, params)
	return &MockClientAPIImportTasksIDImportRunsRunIdStatusGetCall{Call: call}
}

// MockClientAPIImportTasksIDImportRunsRunIdStatusGetCall wrap *gomock.Call
type MockClientAPIImportTasksIDImportRunsRunIdStatusGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientAPIImportTasksIDImportRunsRunIdStatusGetCall) Return(arg0 gen.APIImportTasksIDImportRunsRunIdStatusGetRes, arg1 error) *MockClientAPIImportTasksIDImportRunsRunIdStatusGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientAPIImportTasksIDImportRunsRunIdStatusGetCall) Do(f func(context.Context, gen.APIImportTasksIDImportRunsRunIdStatusGetParams) (gen.APIImportTasksIDImportRunsRunIdStatusGetRes, error)) *MockClientAPIImportTasksIDImportRunsRunIdStatusGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientAPIImportTasksIDImportRunsRunIdStatusGetCall) DoAndReturn(f func(context.Context, gen.APIImportTasksIDImportRunsRunIdStatusGetParams) (gen.APIImportTasksIDImportRunsRunIdStatusGetRes, error)) *MockClientAPIImportTasksIDImportRunsRunIdStatusGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// APIImportTasksIDPatch mocks base method.
func (m *MockClient) APIImportTasksIDPatch(ctx context.Context, request gen.APIImportTasksIDPatchReq, params gen.APIImportTasksIDPatchParams) (gen.APIImportTasksIDPatchRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APIImportTasksIDPatch", ctx, request, params)
	ret0, _ := ret[0].(gen.APIImportTasksIDPatchRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// APIImportTasksIDPatch indicates an expected call of APIImportTasksIDPatch.
func (mr *MockClientMockRecorder) APIImportTasksIDPatch(ctx, request, params any) *MockClientAPIImportTasksIDPatchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APIImportTasksIDPatch", reflect.TypeOf((*MockClient)(nil).APIImportTasksIDPatch), ctx, request, params)
	return &MockClientAPIImportTasksIDPatchCall{Call: call}
}

// MockClientAPIImportTasksIDPatchCall wrap *gomock.Call
type MockClientAPIImportTasksIDPatchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientAPIImportTasksIDPatchCall) Return(arg0 gen.APIImportTasksIDPatchRes, arg1 error) *MockClientAPIImportTasksIDPatchCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientAPIImportTasksIDPatchCall) Do(f func(context.Context, gen.APIImportTasksIDPatchReq, gen.APIImportTasksIDPatchParams) (gen.APIImportTasksIDPatchRes, error)) *MockClientAPIImportTasksIDPatchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientAPIImportTasksIDPatchCall) DoAndReturn(f func(context.Context, gen.APIImportTasksIDPatchReq, gen.APIImportTasksIDPatchParams) (gen.APIImportTasksIDPatchRes, error)) *MockClientAPIImportTasksIDPatchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// APIImportTasksIDStatusGet mocks base method.
func (m *MockClient) APIImportTasksIDStatusGet(ctx context.Context, params gen.APIImportTasksIDStatusGetParams) (*gen.ImportTaskStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APIImportTasksIDStatusGet", ctx, params)
	ret0, _ := ret[0].(*gen.ImportTaskStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// APIImportTasksIDStatusGet indicates an expected call of APIImportTasksIDStatusGet.
func (mr *MockClientMockRecorder) APIImportTasksIDStatusGet(ctx, params any) *MockClientAPIImportTasksIDStatusGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APIImportTasksIDStatusGet", reflect.TypeOf((*MockClient)(nil).APIImportTasksIDStatusGet), ctx, params)
	return &MockClientAPIImportTasksIDStatusGetCall{Call: call}
}

// MockClientAPIImportTasksIDStatusGetCall wrap *gomock.Call
type MockClientAPIImportTasksIDStatusGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientAPIImportTasksIDStatusGetCall) Return(arg0 *gen.ImportTaskStatusResponse, arg1 error) *MockClientAPIImportTasksIDStatusGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientAPIImportTasksIDStatusGetCall) Do(f func(context.Context, gen.APIImportTasksIDStatusGetParams) (*gen.ImportTaskStatusResponse, error)) *MockClientAPIImportTasksIDStatusGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientAPIImportTasksIDStatusGetCall) DoAndReturn(f func(context.Context, gen.APIImportTasksIDStatusGetParams) (*gen.ImportTaskStatusResponse, error)) *MockClientAPIImportTasksIDStatusGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// APIImportTasksPost mocks base method.
func (m *MockClient) APIImportTasksPost(ctx context.Context, request gen.OptAPIImportTasksPostReq) (gen.APIImportTasksPostRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APIImportTasksPost", ctx, request)
	ret0, _ := ret[0].(gen.APIImportTasksPostRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// APIImportTasksPost indicates an expected call of APIImportTasksPost.
func (mr *MockClientMockRecorder) APIImportTasksPost(ctx, request any) *MockClientAPIImportTasksPostCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APIImportTasksPost", reflect.TypeOf((*MockClient)(nil).APIImportTasksPost), ctx, request)
	return &MockClientAPIImportTasksPostCall{Call: call}
}

// MockClientAPIImportTasksPostCall wrap *gomock.Call
type MockClientAPIImportTasksPostCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientAPIImportTasksPostCall) Return(arg0 gen.APIImportTasksPostRes, arg1 error) *MockClientAPIImportTasksPostCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientAPIImportTasksPostCall) Do(f func(context.Context, gen.OptAPIImportTasksPostReq) (gen.APIImportTasksPostRes, error)) *MockClientAPIImportTasksPostCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientAPIImportTasksPostCall) DoAndReturn(f func(context.Context, gen.OptAPIImportTasksPostReq) (gen.APIImportTasksPostRes, error)) *MockClientAPIImportTasksPostCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
