// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SipColumns holds the columns for the "sip" table.
	SipColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 1024},
		{Name: "checksum", Type: field.TypeString, Unique: true, Size: 64},
	}
	// SipTable holds the schema information for the "sip" table.
	SipTable = &schema.Table{
		Name:       "sip",
		Columns:    SipColumns,
		PrimaryKey: []*schema.Column{SipColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SipTable,
	}
)

func init() {
	SipTable.Annotation = &entsql.Annotation{
		Table: "sip",
	}
}
