// Code generated by go-enum DO NOT EDIT.
// Version: 0.9.2
// Revision: 9d73c76728916582359433d1eb0b27340a8268b7
// Build Date: 2025-10-17T20:10:48Z
// Built By: goreleaser

package enums

import (
	"fmt"
	"strings"
)

const (
	EventOutcomeUnspecified       EventOutcome = "unspecified"
	EventOutcomeSuccess           EventOutcome = "success"
	EventOutcomeSystemFailure     EventOutcome = "system failure"
	EventOutcomeValidationFailure EventOutcome = "validation failure"
)

var ErrInvalidEventOutcome = fmt.Errorf("not a valid EventOutcome, try [%s]", strings.Join(_EventOutcomeNames, ", "))

var _EventOutcomeNames = []string{
	string(EventOutcomeUnspecified),
	string(EventOutcomeSuccess),
	string(EventOutcomeSystemFailure),
	string(EventOutcomeValidationFailure),
}

// EventOutcomeNames returns a list of possible string values of EventOutcome.
func EventOutcomeNames() []string {
	tmp := make([]string, len(_EventOutcomeNames))
	copy(tmp, _EventOutcomeNames)
	return tmp
}

// String implements the Stringer interface.
func (x EventOutcome) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x EventOutcome) IsValid() bool {
	_, err := ParseEventOutcome(string(x))
	return err == nil
}

var _EventOutcomeValue = map[string]EventOutcome{
	"unspecified":        EventOutcomeUnspecified,
	"success":            EventOutcomeSuccess,
	"system failure":     EventOutcomeSystemFailure,
	"validation failure": EventOutcomeValidationFailure,
}

// ParseEventOutcome attempts to convert a string to a EventOutcome.
func ParseEventOutcome(name string) (EventOutcome, error) {
	if x, ok := _EventOutcomeValue[name]; ok {
		return x, nil
	}
	return EventOutcome(""), fmt.Errorf("%s is %w", name, ErrInvalidEventOutcome)
}

// Values implements the entgo.io/ent/schema/field EnumValues interface.
func (x EventOutcome) Values() []string {
	return EventOutcomeNames()
}

// EventOutcomeInterfaces returns an interface list of possible values of EventOutcome.
func EventOutcomeInterfaces() []interface{} {
	var tmp []interface{}
	for _, v := range _EventOutcomeNames {
		tmp = append(tmp, v)
	}
	return tmp
}

// ParseEventOutcomeWithDefault attempts to convert a string to a ContentType.
// It returns the default value if name is empty.
func ParseEventOutcomeWithDefault(name string) (EventOutcome, error) {
	if name == "" {
		return _EventOutcomeValue[_EventOutcomeNames[0]], nil
	}
	if x, ok := _EventOutcomeValue[name]; ok {
		return x, nil
	}
	var e EventOutcome
	return e, fmt.Errorf("%s is not a valid EventOutcome, try [%s]", name, strings.Join(_EventOutcomeNames, ", "))
}

// NormalizeEventOutcome attempts to parse a and normalize string as content type.
// It returns the input untouched if name fails to be parsed.
// Example:
//
//	"enUM" will be normalized (if possible) to "Enum"
func NormalizeEventOutcome(name string) string {
	res, err := ParseEventOutcome(name)
	if err != nil {
		return name
	}
	return res.String()
}
