// Code generated by go-enum DO NOT EDIT.
// Version: 0.9.2
// Revision: 9d73c76728916582359433d1eb0b27340a8268b7
// Build Date: 2025-10-17T20:10:48Z
// Built By: goreleaser

package enums

import (
	"fmt"
	"strings"
)

const (
	SIPTypeDigitizedAIP   SIPType = "DigitizedAIP"
	SIPTypeDigitizedSIP   SIPType = "DigitizedSIP"
	SIPTypeBornDigitalAIP SIPType = "BornDigitalAIP"
	SIPTypeBornDigitalSIP SIPType = "BornDigitalSIP"
)

var ErrInvalidSIPType = fmt.Errorf("not a valid SIPType, try [%s]", strings.Join(_SIPTypeNames, ", "))

var _SIPTypeNames = []string{
	string(SIPTypeDigitizedAIP),
	string(SIPTypeDigitizedSIP),
	string(SIPTypeBornDigitalAIP),
	string(SIPTypeBornDigitalSIP),
}

// SIPTypeNames returns a list of possible string values of SIPType.
func SIPTypeNames() []string {
	tmp := make([]string, len(_SIPTypeNames))
	copy(tmp, _SIPTypeNames)
	return tmp
}

// String implements the Stringer interface.
func (x SIPType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x SIPType) IsValid() bool {
	_, err := ParseSIPType(string(x))
	return err == nil
}

var _SIPTypeValue = map[string]SIPType{
	"DigitizedAIP":   SIPTypeDigitizedAIP,
	"DigitizedSIP":   SIPTypeDigitizedSIP,
	"BornDigitalAIP": SIPTypeBornDigitalAIP,
	"BornDigitalSIP": SIPTypeBornDigitalSIP,
}

// ParseSIPType attempts to convert a string to a SIPType.
func ParseSIPType(name string) (SIPType, error) {
	if x, ok := _SIPTypeValue[name]; ok {
		return x, nil
	}
	return SIPType(""), fmt.Errorf("%s is %w", name, ErrInvalidSIPType)
}

// Values implements the entgo.io/ent/schema/field EnumValues interface.
func (x SIPType) Values() []string {
	return SIPTypeNames()
}

// SIPTypeInterfaces returns an interface list of possible values of SIPType.
func SIPTypeInterfaces() []interface{} {
	var tmp []interface{}
	for _, v := range _SIPTypeNames {
		tmp = append(tmp, v)
	}
	return tmp
}

// ParseSIPTypeWithDefault attempts to convert a string to a ContentType.
// It returns the default value if name is empty.
func ParseSIPTypeWithDefault(name string) (SIPType, error) {
	if name == "" {
		return _SIPTypeValue[_SIPTypeNames[0]], nil
	}
	if x, ok := _SIPTypeValue[name]; ok {
		return x, nil
	}
	var e SIPType
	return e, fmt.Errorf("%s is not a valid SIPType, try [%s]", name, strings.Join(_SIPTypeNames, ", "))
}

// NormalizeSIPType attempts to parse a and normalize string as content type.
// It returns the input untouched if name fails to be parsed.
// Example:
//
//	"enUM" will be normalized (if possible) to "Enum"
func NormalizeSIPType(name string) string {
	res, err := ParseSIPType(name)
	if err != nil {
		return name
	}
	return res.String()
}
