apiVersion: v1
kind: Secret
metadata:
  name: sfa-dips-secret
type: Opaque
stringData:
  sfa-dips.toml: |
    # logFormat controls the encoding of application log messages. Supported
    # values are "json" for structured output and "text" for human-readable,
    # colorized output.
    logFormat = "text"
    # verbosity supports values from 0-128, with 0 as least verbose and 128
    # capturing all possible log events.
    verbosity = 2

    [api]
    # Address of the API server.
    listen = ":8080"

    # CORS Access-Control-Allow-Origin policy for the API server. Defaults to the
    # listen address if not set.
    corsOrigin = "*"

    [api.log]
    # Path to the API log file. Accepts stdout or stderr for console output. If
    # `path` is not set, or set to an empty string, logging is disabled.
    path = "stdout"

    # Log level sets the log verbosity. Valid values are: "debug", "info" (default),
    # "warn", and "error" (case-insensitive).
    level = "warn"

    # Format of the log messages. Valid values are: "json" (default) and "text".
    format = "text"

    [api.auth]
    # Enable API authentication. OIDC is the only protocol supported at the
    # moment. When enabled the API verifies the access token submitted with
    # each request. Clients are responsible for obtaining an access token
    # from a configured OIDC provider below.
    enabled = true

    # Multiple OIDC providers are supported. Add one `[[api.auth.oidc]]` table
    # per provider/client pair.
    #
    # [[api.auth.oidc]]
    # providerURL = "http://keycloak:7470/realms/artefactual"
    # clientID = "enduro"
    # [[api.auth.oidc]]
    # providerURL = "http://keycloak:7470/realms/artefactual-internal"
    # clientID = "enduro-s2s"
    # skipEmailVerifiedCheck = true
    [[api.auth.oidc]]
    # OIDC provider URL. Required when auth. is enabled.
    providerURL = "http://keycloak:7470/realms/artefactual"
    # OIDC client ID. The client ID must be included in the `aud` claim of
    # the access token. Required when auth. is enabled.
    clientID = "enduro-s2s"
    # Do not check if the `email_verified` claim is present and set to `true`.
    skipEmailVerifiedCheck = true

    [persistence]
    driver = "mysql"
    dsn = ""
    migrate = true

    [temporal]
    address = "temporal-frontend.enduro-sdps:7233"
    namespace = "default"
    taskQueue = "sfa-dips"
    maxConcurrentSessions = 1
