apiVersion: apps/v1
kind: Deployment
metadata:
  name: apis-mock
  labels:
    app: apis-mock
spec:
  selector:
    matchLabels:
      app: apis-mock
  template:
    metadata:
      labels:
        app: apis-mock
    spec:
      serviceAccountName: sdps
      containers:
        - name: apis-mock
          image: apis-mock:dev
          ports:
            - containerPort: 8080
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: apis-mock
  labels:
    app: apis-mock
spec:
  selector:
    app: apis-mock
  ports:
    - port: 8080
