on:
  pull_request:
  push:
    branches:
      - main
name: Validate Tilt
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install kubectl and Tilt
        uses: yokawasa/action-setup-kube-tools@v0.13.4
        with:
          setup-tools: |
            kubectl
            tilt
      - name: Validate Tiltfile
        run: make validate-tilt
